### ISSUE TITLE
Improve default coloring contrast

### ISSUE THREAD

**Issue by xeruf** [mookid/diffr#72] opened 2021-01-19 09:55 UTC
IntelliJ Idea Terminal:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/13354331/105017129-bc191080-5a43-11eb-8c4a-a813e26eef9c.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/13354331/105017226-d3f09480-5a43-11eb-994c-cbb9f579c54b.png">
Konsole:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/13354331/105017284-e2d74700-5a43-11eb-8f81-94f3e7f8dc81.png">

I understand that the tool should by default only highlight the character changes and leave everything else untouched - however, white on bright green is barely legible, especially if, as in the first two examples the white isn't a pure white.

Couldn't you use a dark green background or smth?

### Relation

Seems this originates from #31 - if the reason is that you don't want to add any colors, maybe you could make the text on the green background black again. 

> I figured, the reason is that "black" color more likely to blend with the dark "green" and "red" than white color.

Idk why, but in my case it is a bright and not a dark green ^^

**Comment by mookid** [comment] 2021-01-19 10:11
I see the same thing from vscode; there I added "terminal.ansiBrightWhite": "#EEEEEE" in the config.

default:
![image](https://user-images.githubusercontent.com/7757342/105019978-02bc3a00-5a47-11eb-96cd-d0ceff392931.png)

with the new setting:
![image](https://user-images.githubusercontent.com/7757342/105019933-f637e180-5a46-11eb-9788-9d7a50d6561d.png)

does that help?

**Comment by xeruf** [comment] 2021-01-19 10:47
it seems that ansi white is already supposed to be white in the terminal:
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/13354331/105024022-e79ff900-5a4b-11eb-838f-ed6d9e127ba4.png">

either way, that doesn't change the fact that even in a normal terminal the contrast of pure white on bright green is barely legible

**Comment by mookid** [comment] 2021-01-19 10:52
in that case, you should use the appropriate flags to change the foreground color to something you like; it is unlikely that a single set of default settings is perfect for each scenario.

**Comment by xeruf** [comment] 2021-01-19 11:49
can you show me any case where white on green works well? None of the screenshots in this thread indicate that.

**Comment by mookid** [comment] 2021-01-19 15:44
the second screenshot I posted renders as intended.

The option to change to almost any styling available in the console is given via the --colors flag, so that users are not stuck because of defaults.

About the defauIt config, I welcome any proposal, under the following constrains:
- the same config should work out of the box on all supported OSs (which limits to a 16 colors palette because of the windows console)
- bonus points for added=green, removed=red (because this is how git diff styles the diff)

**Comment by xeruf** [comment] 2021-01-20 09:52
> the second screenshot I posted renders as intended.

yes, I know that that is the currently intended state, but we can agree that white on bright green is not sufficient contrast?

Does the default currently use ANSI green or bright green? I think simply using a darker color (ideally still green) as background would be fine.

**Comment by Hi-Angel** [comment] 2023-01-20 02:17
> can you show me any case where white on green works well? None of the screenshots in this thread indicate that.

None of the "bad" screenshots show white letters though. I mean, look, it is clearly gray not white. This thread so far has just two shots where white is an actual white and I don't think you'd deny it works in these two cases.

So, that's the real problem: white not being white.

And I think I know a solution. Look at this table:

![image](https://user-images.githubusercontent.com/7935057/213603964-abe0a7a2-61a9-4f40-910d-903c82a597e5.png)


The real white is called "bright white", whereas "white" most often is shown as gray.

So setting the color to "bright white" should fix that.

**Comment by Hi-Angel** [comment] 2023-01-20 03:08
Should be fixed by #83

**Closed as completed** 2023-01-20 09:27 UTC
